spring.application.name=moveflix
spring.mvc.servlet.path=/moveflix

# Swagger config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/v3/api-docs

# Banco da aplicacao
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/moveflix}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:adminadmin}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
