#Para rodar testes no GitHub Actions com PostgreSQL
# Nome da aplicação
spring.application.name=moveflix-ci

# Caminho base
spring.mvc.servlet.path=/moveflix

# Banco PostgreSQL (ajustável por variáveis no GitHub Actions)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/moveflix}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:adminadmin}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Swagger (desativar para CI, opcional)
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Health check
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
