# Para testes locais com H2 (usado quando você roda mvn test -Dspring.profiles.active=test)
# Nome da aplicação
spring.application.name=moveflix-test

# Caminho base do servlet (pode manter igual)
spring.mvc.servlet.path=/moveflix

# Banco H2 em memória
spring.datasource.url=jdbc:h2:mem:moveflixtest;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# Swagger (opcional nos testes)
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Ativa detalhes do health check
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
